#define PJ_CONFIG_IPHONE 1

#define PJMEDIA_HAS_G729_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_G711_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 1
#define PJMEDIA_HAS_G7221_CODEC 0
#define PJMEDIA_HAS_L16_CODEC 0

#define PJSIP_DONT_SWITCH_TO_TCP 1

#define PJMEDIA_HAS_OPUS_CODEC   1
#define PJMEDIA_HAS_SRTP 0

#define PJSIP_MAX_PKT_LEN                       10000

#include <pj/config_site_sample.h>

