//
//  VoipUsageConst.h
//  TouchPalDialer
//
//  Created by lingmeixie on 16/8/30.
//
//

#ifndef VoipUsageConst_h
#define VoipUsageConst_h

#define CALL_ID @"callId"
#define CALL_TYPE @"callType"/*0:outgoing 1:incoming 2:callback*/
#define INFO_FLOW @"infoFlow"
#define STATUS_FLOW @"statusFlow"
#define CHANNEL @"channel"
#define VER @"ver"
#define SYSTEM @"system"
#define IMEI @"imei"
#define EDGE @"edge"
#define MAC @"mac"
#define NETWORK_NAME @"networkName"
#define NETWORK_TYPE @"networkType"
#define NETWORK_SUB_TYPE @"networkSubType"
#define CALLER @"caller"
#define CALLEE @"callee"
#define WIFI_BSSID @"wifiBssid"
#define CALL_C2X @"callC2X"/*1:ctop 2:ctoc*/
#define IS_ANSWERED @"isAnswered"
#define FINAL_BEV @"finalBev"
#define IS_ROMAING @"isRoaming"
#define CITY @"city"
#define LATITUDE @"latitude"
#define LONGITUDE @"longitude"
#define INVITE_START @"inviteStart"
#define TALK_START @"talkStart"
#define RING_START @"ringStart"
#define FINISH_TIME @"finishTime"
#define LAST_STATE @"lastState"
#define PLATFORM @"platform"
#define TXTOAL @"txTol"
#define TXDIS @"txDis"
#define TXDUP @"txDup"
#define TXLOSS @"txLoss"
#define TXRECORDER @"txRecorder"
#define RXRECORDER @"rxRecorder"
#define OPTION_REQUEST_TIME  @"optionsReqTime"
#define OPTION_RESPONSE_TIME @"optionsRespTime"
#define RTP_SERVER_CANDINATE @"rtpServerCands"
#define RTP_SELECT_CANDINATE @"rtpSelection"
#define RTP_SELECT_TIME @"rtpSelectedTime"
#define RXTOL @"rxTol"
#define RXDIS @"rxDis"
#define RXDUP @"rxDup"
#define RXLOSS @"rxLoss"
#define FEC_PUT_FAKE_CNT @"fecPutFakeCnt"
#define RTP_RESEND_CNT @"rtpResendCnt"

#define FEC_GROUP_DEL_CNT @"fecGrpDelCnt"
#define FEC_RX_TOL @"fecRxtol"
#define FEC_LOSS_PKT @"fecLossPkt"
#define FEC_REPAIR_PKT @"fecRepairPkt"
#define FEC_GROUP_CNT @"fecGroupCnt"
#define FEC_INVALID_GROUP_CNT @"fecInvalidGroupCnt"
#define FEC_LIST_BURST_CNT @"fecListBurstCnt"
#define FEC_LIST_EMPTY_CNT @"fecListEmptyCnt"
#define FEC_LIST_PREFECT_CH_CNT @"fecListPrefetchCnt"
#define FEC_PUT_DECODER_CNT @"fecPutDecoderCnt"
#define FEC_SEQ_JUMP_CNT @"fecSeqJumpCnt"
#define FEC_TOOL_LATE_CNT @"fecTooLateCnt"
#define FEC_PKT_SEQ_ERR_CNT @"fecPktSeqErrCnt"
#define FEC_GRP_PKT_MISS_1 @"fecGrpPktMiss1"
#define FEC_GRP_PKT_MISS_2 @"fecGrpPktMiss2"
#define FEC_GRP_PKT_MISS_3 @"fecGrpPktMiss3"
#define FEC_GRP_PKT_MISS_4 @"fecGrpPktMiss4"
#define FEC_PUT_SRC_CNT @"fecPutSrcCnt"
#define FEC_SEC_REPAIRE_CNT @"fecSecRepairPkt"
#define FEC_LOW_RECV_RATE_CNT @"fecLowRecvRateCnt"
#define BUF_NORMAL_FRAME @"jbufNormalFrame"
#define BUF_MISS_FRAME @"jbufMissFrame"
#define BUF_ZERO_FRAME @"jbufZeroFrame"
#define BUF_PREFECT_ZERO_FRAME @"jbufPrefetchZeroFrame"
#define BUF_EMPTY_OCCUR_CNT @"jbufEmptyOccurredCnt"
#define BUF_MAX_EMPTY_FRAME @"jbufMaxEmptyFrame"
#define BUF_SIZE @"jbufSize"
#define BUF_BURST @"jbufBurst"
#define BUF_AVG_BURST @"jbufAvgBurst"
#define BUF_DISCARD @"jbufDiscard"
#define BUF_EMPTY @"jbufEmpty"
#define BUF_LOST @"jbufLost"
#define FINAL_POST_KID @"finalPostkid"
#define CALLBACKINCOMING @"callbackincoming"
#define CALLBACKTYPE @"callbackType"
#define POSTKID_FLOW @"postKidsFlow"
#define INVALID_INFO_FLOW @"invalidInfo"
#define RELAY_1 @"relay1"
#define RELAY_2 @"relay2"
#define GAP_STAT @"gapStat"
#define TS_DELAY_INFO @"tsDelayInfo"
#endif /* VoipUsageConst_h */
